# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import logging
from PyQt5 import QtCore, QtGui, QtWidgets
from style import AddStyles
import sys
import subprocess
from database import PDVClasse
import psycopg2


class Ui_Login(object):
    def setupUi(self, MainWindow):

        self.add_styles_instance = AddStyles()
        


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet(self.add_styles_instance.style_top())
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")


        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet(self.add_styles_instance.style_content())
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")


        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMaximumSize(QtCore.QSize(450, 16777215))
        self.login_area.setStyleSheet(self.add_styles_instance.style_login_area())
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")


        self.logo = QtWidgets.QFrame(self.login_area)
        self.logo.setGeometry(QtCore.QRect(123, 70, 211, 201))
        self.logo.setStyleSheet(self.add_styles_instance.style_logo())
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")


        self.lineEdit_user = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_user.setGeometry(QtCore.QRect(104, 350, 241, 51))
        self.lineEdit_user.setStyleSheet(self.add_styles_instance.style_user())
        self.lineEdit_user.setObjectName("lineEdit_user")


        self.lineEdit_password = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_password.setGeometry(QtCore.QRect(104, 410, 241, 51))
        self.lineEdit_password.setStyleSheet(self.add_styles_instance.style_password())
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")


        self.checkBox_save = QtWidgets.QCheckBox(self.login_area)
        self.checkBox_save.setGeometry(QtCore.QRect(110, 470, 231, 31))
        self.checkBox_save.setStyleSheet(self.add_styles_instance.style_check())
        self.checkBox_save.setObjectName("checkBox_save")


        self.pushButton_login = QtWidgets.QPushButton(self.login_area)
        self.pushButton_login.setGeometry(QtCore.QRect(104, 510, 241, 41))
        self.pushButton_login.setStyleSheet(self.add_styles_instance.style_login())
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_login.clicked.connect(self.login)

        self.pushButton_login1 = QtWidgets.QPushButton(self.login_area)
        self.pushButton_login1.setGeometry(QtCore.QRect(104, 610, 241, 40))
        self.pushButton_login1.setStyleSheet(self.add_styles_instance.style_login())
        self.pushButton_login1.setObjectName("pushButton_login")
        self.pushButton_login1.clicked.connect(self.open_main_register)


        self.horizontalLayout.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        self.botton_bar = QtWidgets.QFrame(self.centralwidget)
        self.botton_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.botton_bar.setStyleSheet(self.add_styles_instance.style_buttom_bar())
        self.botton_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.botton_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.botton_bar.setObjectName("botton_bar")

        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.botton_bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_credit = QtWidgets.QLabel(self.botton_bar)
        self.label_credit.setStyleSheet("color: #7f7a7a;")
        self.label_credit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credit.setObjectName("label_credit")
        self.verticalLayout_2.addWidget(self.label_credit)
        self.verticalLayout.addWidget(self.botton_bar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_user.setText(_translate("MainWindow", "USER"))
        self.lineEdit_password.setText(_translate("MainWindow", "PASSWORD"))
        self.checkBox_save.setText(_translate("MainWindow", "SAVE USER"))
        self.pushButton_login.setText(_translate("MainWindow", "Connect"))
        self.pushButton_login1.setText(_translate("MainWindow", "Register"))
        self.label_credit.setText(_translate("MainWindow", "Created by: Herberth Amorim"))

#Funções ###########################################################################################################################################################################################################################



    def open_main_register(self):
        subprocess.run(["python", "Register.py"])

    def open_main_window(self):
        subprocess.run(["python", QtWidgets.QApplication.quit()])

    def login(self):
        username = self.lineEdit_user.text()
        password = self.lineEdit_password.text()

        pdv = PDVClasse()

        # Verificar as credenciais de login
        if pdv.verificar_credenciais(username, password):
            MainWindow.hide()
            self.open_main_window()
            # Oculta a janela de login
        else:
            QtWidgets.QMessageBox.warning(self.login_area, "Login Inválido", "Usuário ou senha incorretos.")




import file_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())